baseURL = "https://shouryaps.com/"
languageCode = "en-us"
title = "@shouryaps"
themesDir = "themes"
theme = "hugo-shouryaps-blog-theme"

paginate = 5

[module]
[module.hugoVersion]
extended = true
min = "0.55.0"

[params]
twitterHandle = "@shouryaps"

twitterUsername = "shouryaps"
linkedinUsername = "shouryaps"
githubUsername = "shouryaps"

introMD = "**Shourya's** Home on Internet"

showPostsOnHomepage = true
maxHomepagePosts = 2

addDot = true

highlightColor = '#113CFC'

[taxonomies]
tag = "tags"
